import type { FulfillmentOrder } from "@/types/proses-pesanan/fulfillment";
import type { Order, OrderItem, OrderStatus } from "@/types/pesanan/order";

export function fulfillmentToOrder(f: FulfillmentOrder): Order {
  const items: OrderItem[] = f.items.map((i) => ({
    id: i.id,
    item_id: null,
    channel_product_id: null,
    sku: i.sku,
    description: i.description,
    qty_in_base: i.qty,
    price: 0,
    disc: 0,
    disc_amount: 0,
    tax_amount: 0,
    amount: 0,
    image_url: i.imageUrl,
  }));

  return {
    id: f.id,
    salesorder_no: f.salesorderNo,
    channel_order_no: f.channelOrderNo,
    source: f.source,
    channel_shop_id: null,
    shop_name: null,
    customer_name: f.customerName ?? "",
    transaction_date: f.transactionDate,
    status: (f.status ?? "reserved") as OrderStatus,
    channel_status: null,
    is_paid: f.isPaid,
    is_canceled: f.isCanceled,
    cancel_reason: f.cancelReason,
    cancel_requested_at: f.cancelRequestedAt,
    cancel_request_reason: null,
    cancel_accepted_at: f.cancelAcceptedAt,
    cancel_channel: null,
    handed_to_warehouse_at: null,
    payment_method: null,
    payment_method_name: null,
    paid_time: null,
    sub_total: 0,
    total_disc: 0,
    total_tax: 0,
    shipping_cost: f.actualShippingFee ?? 0,
    insurance_cost: 0,
    grand_total: f.grandTotal,

    finance: {
      seller_voucher: null,
      platform_voucher: null,
      payment_voucher: null,
      commission_fee: null,
      service_fee: null,
      transaction_fee: null,
      affiliate_commission: null,
      order_processing_fee: null,
      seller_shipping_borne: null,
      platform_shipping_rebate: null,
      settlement_amount: null,
      currency: "IDR",
      is_settled: false,
      synced_at: null,
    },
    shipping: {
      full_name: f.customerName,
      phone: null,
      address: null,
      city: null,
      province: null,
      post_code: null,
      country: null,
      provider: f.shippingProvider,
      tracking_number: f.trackingNumber,
    },
    buyer_message: null,
    seller_note: null,
    location_id: f.locationId,
    location_name: f.locationName,
    total_qty: f.totalQty ?? 0,
    total_sku: f.totalSku ?? 0,
    items,
    received_date: null,
    ship_by_date: f.shipByDate ?? null,
    created_at: f.transactionDate ?? "",
    updated_at: f.transactionDate ?? "",
  };
}
